### PR TITLE
Stringattr

### PR DESCRIPTION
**Pull request by doughunt**
Hi Ed:  Now I seem to have ssh access with my newly created key.  The incantation which worked was:

git push -u git@github.com:PDLPorters/PDL-NetCDF.git stringattr

Now I'll create this pull request and then (hopefully) you can take a look at my changes.
Please give a look at my XS code, I have not done with sort of programming for 10 or 15 years.

Take care, 

  Doug

### CODE REVIEW

**Comment by oalders** [comment]
I believe the target repo for this PR should actually be https://github.com/PDLPorters/PDL-NetCDF

@mohawk2 can likely confirm?

**Comment by mohawk2** [comment]
> I believe the target repo for this PR should actually be https://github.com/PDLPorters/PDL-NetCDF
> 
> @mohawk2 can likely confirm?

I can confirm! The problem is that https://github.com/PDLPorters/PDL-NetCDF is a fork, and I don't know how to make it stop being such.

**Comment by mohawk2** [comment]
Also, the only commits visible on the `stringattr` branch are the current `master` on the PDLPorters repo, which isn't very useful.

**Comment by doughunt** [comment]
Hi all:  If I try to push to that URL, it asks me for a user id and 
password.  I respond 'doughunt' and give it either my github password or 
the personal access token I just
created and it fails:



then:



If I instead push this way, it seems to work.  I also tried to open up a 
merge request.  Did you gen any such notice?



Regards,

   Doug

**Comment by mohawk2** [comment]
It turns out it's easy to "detach" a fork now! https://ralphjsmit.com/unfork-github-repo

**Comment by mohawk2** [comment]
@doughunt My use of that URL wasn't to ask you to `git push` to it, just to indicate which repo to use :-) Let's continue this conversation by email or possibly a PR on the PDLPorters repo.

**Comment by mohawk2** [comment]
> It turns out it's easy to "detach" a fork now! https://ralphjsmit.com/unfork-github-repo

And they've already finished it!

**Pull request closed without merging**
